spring: 
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: admin
    url: jdbc:mysql://127.0.0.1:3306/springbootdb?characterEncoding=utf-8
mybatis:
  type-aliases-package: com.dyz.entity
  mapper-locations:
  - classpath:mapper/*.xml
logging:
  level:
    com: 
     dyz: 
      dao: debug